---
apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/kutumbaburumba/app-of-apps.git
  password: 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
  username: kirill.yasinovskiy@computacenter.com