apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
  - workflow-sa.yaml
  - azure-devops-creds.yaml
  - simple-git-workflow.yaml
patchesStrategicMerge:
  - workflow-controller-configmap.yaml