apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      Checkout out from Git and test 
    workflows.argoproj.io/tags: git
    workflows.argoproj.io/version: '>= 2.9.0'
  name: input-artifact-git
  namespace: argo
spec:
  serviceAccountName: argo-workflow
  entrypoint: main
  arguments:
    parameters:
      - name: repo
        value: https://msg-services-marketplace-saas@dev.azure.com/msg-services-marketplace-saas/applications/_git/test-application
      - name: branch
        value: main
      - name: output
        value: test-application
  templates:
    - name: main
      steps:
        - - name: checkout
            template: checkout
        - - name: git-status
            template: git-status
    - name: checkout
      script:
        image: golang:1.17
        workingDir: /work
        args: [sh]
        source: | 
          MY_PAT=4tq4cxmdvdqgacrwds2pfyahlaurdty73lrr5bttqlb3wocpm74a
          B64_PAT=$(printf "%s"":$MY_PAT" | base64)
          git -c http.extraHeader="Authorization: Basic ${B64_PAT}" clone --depth 1 --single-branch --branch {{workflow.parameters.branch}} {{workflow.parameters.repo}} .
        volumeMounts:
          - mountPath: /work
            name: work
    - name: git-status
      script:
        image: golang:1.17
        workingDir: /work
        args:
          - sh
        source: git status && ls && cat README.md
        volumeMounts:
          - mountPath: /work
            name: work
  volumeClaimTemplates:
    # A shared work volume.
    - name: work
      metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 64Mi


