apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.0.10"
  - ./workflow-controller-configmap.yaml
  - ./workflow-sa.yaml