apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: workflow
  namespace: argo-events
  finalizers:
    - sensor-controller
spec:
  serviceAccountName: operate-workflow-sa
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: payload
      eventSourceName: webhook
      eventName: create-cluster
  triggers:
    - template:
        name: webhook-workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          resource: Workflow
          operation: submit
          metadata:
            generateName: cluster-workflow-template-hello-world-
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-input-artifact-git-
              spec:
                serviceAccountName: argo-workflow
                entrypoint: main
                arguments:
                  parameters:
                  - name: branch
                    value: "from trigger"
                workflowTemplateRef:
                  name: input-artifact-git
                  clusterScope: true
          parameters:
            - src:
                dependencyName: payload
                dataKey: body.branch
              dest: spec.arguments.parameters.0.value