---
# event source for all webhooks
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 10000
        targetPort: 10000
  webhook:
    # name of the webhook-event
    create-cluster:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /create-cluster
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
    # define other webhooks here

# Uncomment to use secure webhook
#    secure-examle:
#      port: "13000"
#      endpoint: "/secure"
#      method: "POST"
#      # k8s secret that contains the cert
#      serverCertSecret:
#        name: my-secret
#        key: cert-key
#      # k8s secret that contains the private key
#      serverKeySecret:
#        name: my-secret
#        key: pk-key