apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# "clustered" all-in-one installation (including event-bus)
resources:
  - "github.com/argoproj/argo-events/manifests/cluster-install?ref=v1.4.0"
  - event-bus.yaml